### ISSUE TITLE
plugin?

### ISSUE THREAD

**Issue by psifertex** [mrphrazer/obfuscation_detection#1]
Are you interested in a PR to add a plugin.json so this could be used either in headless mode on the command-line or via the UI inside BN itself which would let it be installable via the plugin manager?

**Comment by mrphrazer** [comment]
yeah I guess that would be nice. it's a very simple script but perhaps it will reach more people then

**Comment by psifertex** [comment]
Yeah, that's the main advantage. Plus, faster to find out if an API bit-rots and easier for us to have one list of places to check for API usage whenever we are considering making API-breaking changes. Closing this now, PR incoming. Also, if you watch the end of the live stream video from this week you'll see the remaining parts of the process. :-)
