### ISSUE TITLE
(not an issue) A thank you word! 

### ISSUE THREAD

**Issue by loneicewolf** [mrphrazer/obfuscation_detection#6]
Hello! This is NOT an issue, or a idea. It's simply a thank you word for making this repo. It's marvelous. Well structured too!

**Comment by loneicewolf** [comment]
Also, just for the context. This can be closed.  I just need to write these thank you's when I stumble upon marvelous projects (**Projects like this one**)

**Comment by mrphrazer** [comment]
Thanks a lot! :)
